language: ruby
rvm:
  - 2.2.0
cache: bundler
env:
  - 'DATABASE_URL=postgres://postgres@localhost:5432/test'
before_script:
  - psql -c 'create database test' -U postgres
  - bundle exec rake db:migrate db:seed
script: bundle exec rspec
